name: CI/CD workflow
on: [pull_request]

jobs:
  rubocop:
    name: Code style suggestions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Prepare Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4.6
          bundler-cache: true
      - name: Rubocop report
        env:
          FORCE_COLOR: 1
        run: bundle exec rubocop --color --fail-fast
